### ISSUE TITLE
Не выполняется запрос из примера в документации

### ISSUE THREAD

**Issue by KonstantinKlychkov** [WLM1ke/aiomoex#2]
При выполнении примера функции из документации вываливается ошибка

---------------------------------------------------------------------------
`import asyncio

import aiomoex
import pandas as pd

async def main():
    request_url = ('https://iss.moex.com/iss/engines/stock/'
                   'markets/shares/boards/TQBR/securities.json')
    arguments = {'securities.columns': ('SECID,'
                                        'REGNUMBER,'
                                        'LOTSIZE,'
                                        'SHORTNAME')}
    iss = aiomoex.ISSClient(request_url, arguments)
    iss.start_session()
    data = await iss.get()
    df = pd.DataFrame(data['securities'])
    df.set_index('SECID', inplace=True)
    print(df.head(), '\n')
    print(df.tail(), '\n')
    df.info()
    await iss.close_session()

asyncio.run(main())`

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-64d69c545a6a> in <module>
     23 
     24 
---> 25 asyncio.run(main())

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35 

RuntimeError: asyncio.run() cannot be called from a running event loop

**Comment by WLM1ke** [comment]
> 34 "asyncio.run() cannot be called from a running event loop")
> 35
> 
> RuntimeError: asyncio.run() cannot be called from a running event loop

Это точно весь код, который вы запускали?
Cудя по трейсу, вы вызываете asyncio.run() не напрямую, а из где-то созданного event loop. 
Можете запушить куда-нибудь весь код, который вы использовали?

**Comment by WLM1ke** [comment]
Покопал в интернете. Есть подозрение, что вы запускаете это не из py файла, а из ноутбука. Ноутбук неявно запускает event loop. 

Есть два решения:

- скопировать код в py файл
- или в ноутбуке заменить строчку asyncio.run(main()) на await main()

Напишите, починилось или нет?

Если вы не сильно владеет Python, то возможно не стоит связываться с asyncio и async/await - это несколько продвинутая тема. У меня есть более классическая реализация такого же функционала в библиотечке https://github.com/WLM1ke/apimoex. Она тоже ставится с помощью pip

**Comment by KonstantinKlychkov** [comment]
Да, вы правы. Я запускаю код из Jupyter notebook. Замена asyncio.run(main()) на await main() помогает в версии python 3.8.1, но в версии 3.6.10 появляется другая ошибка. Кажется в версии 3.6 asyncio был немного другим. Попробую погуглить.

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-0ee7c276d963> in <module>
     23 
     24 
---> 25 await(main())

NameError: name 'await' is not defined

**Comment by WLM1ke** [comment]
Скобки не надо ставить — у вас получается вызов функции await. await не функция, а ключевое слово в Питон, которое означает ожидание результата исполнения корутины. Пишется await потом пробел потом корутина (специальный вид асинхронных функций async def):

await main()

Посмотрите примеры синтаксиса в соответствующем разделе help python https://docs.python.org/3/library/asyncio-task.html
https://www.python.org/dev/peps/pep-0492/

**Comment by KonstantinKlychkov** [comment]
Работает, спасибо за подсказку. Пойду поучу asynio еще немного.
