### ISSUE TITLE
вопрос - как получить свечи для "Календарный спред"

### ISSUE THREAD

**Issue by SatCat** [WLM1ke/aiomoex#6]
Приветствую!
Отличный клиент  для моекс!
Но не могу получить свечи для инструмента RIM3RIU3. (это календ.спред - https://www.moex.com/ru/spreads/)
Или это не возможно?

**Comment by WLM1ke** [comment]
Если честно не знаю, так как не интересовался такими инструментами - можно, то по чему на сайте MOEX есть график со свечами. Если вы мне скинете ссылку на такой график, то пытаюсь помочь

**Comment by SatCat** [comment]
на сайте у них только табличная история дневок https://www.moex.com/ru/derivatives/spreads/archive-spreads.aspx?code=INR-6.23-9.23
графиков не находил.
наверное не доступно, жаль

**Comment by WLM1ke** [comment]
Видимо да
